name: docker-rails-ci

on:
  pull_request:
    branches: [develop]
  push:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose-run
        run: |
          docker-compose up -d
          docker-compose exec -T web bundle exec rubocop
