name: docker-rails-ci

on:
  pull_request:
    branches: [develop]
  push:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.2
      - name: install bundler
        run: |
          gem install bundler
      - name: Cache gems
        uses: actions/cache@preview
        with:
          path: vendor/bundle
          key: gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gem-
      - name: bundle install
        run: |
          bundle install --jobs 4 --retry 3
      - name: lint
        run: bundle exec rubocop

      # - name: rspec
      #   run: bundle exec rspec

      # Pull the latest image to build, and avoid caching pull-only images.
      # (docker pull is faster than caching in most cases.)
      # - run: docker-compose pull

      # In this step, this action saves a list of existing images,
      # the cache is created without them in the post run.
      # It also restores the cache if it exists.
      # - uses: satackey/action-docker-layer-caching@v0.0.11
      #   # Ignore the failure of a step and avoid terminating the job.
      #   continue-on-error: true
      #   with:
      #     key: docker-save-${{ hashFiles('Dockerfile') }}
      #     restore-keys: |
      #       docker-cache-
